site_name: AMI Predict
site_description: Prediction engines and modeling toolkit
repo_url: https://github.com/Independent-AI-Labs/AMI-PREDICT
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Concepts:
      - Data Providers: concepts/data-providers.md
      - Feature Engineering: concepts/features.md
      - Models: concepts/models.md
      - Backtesting & Metrics: concepts/backtesting.md
      - Simulation Engine: concepts/simulation.md
      - Configuration: concepts/configuration.md
  - Guides:
      - Build a Custom Provider: guides/custom-provider.md
      - Train with LightGBM/CatBoost: guides/training-lightgbm.md
      - Acceleration (Intel XPU/CPU): guides/acceleration-xpu.md
      - Experiment Tracking: guides/experiment-tracking.md
      - Web Dashboard Integration: guides/web-dashboard.md
  - API Reference:
      - About: api/README.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

